// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_storage_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_storage_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_storage_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_storage_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_storage_5fservice_2eproto;
namespace storage_service {
class GetPageRequest;
struct GetPageRequestDefaultTypeInternal;
extern GetPageRequestDefaultTypeInternal _GetPageRequest_default_instance_;
class GetPageRequest_PageID;
struct GetPageRequest_PageIDDefaultTypeInternal;
extern GetPageRequest_PageIDDefaultTypeInternal _GetPageRequest_PageID_default_instance_;
class GetPageResponse;
struct GetPageResponseDefaultTypeInternal;
extern GetPageResponseDefaultTypeInternal _GetPageResponse_default_instance_;
class LogWriteRequest;
struct LogWriteRequestDefaultTypeInternal;
extern LogWriteRequestDefaultTypeInternal _LogWriteRequest_default_instance_;
class LogWriteResponse;
struct LogWriteResponseDefaultTypeInternal;
extern LogWriteResponseDefaultTypeInternal _LogWriteResponse_default_instance_;
}  // namespace storage_service
PROTOBUF_NAMESPACE_OPEN
template<> ::storage_service::GetPageRequest* Arena::CreateMaybeMessage<::storage_service::GetPageRequest>(Arena*);
template<> ::storage_service::GetPageRequest_PageID* Arena::CreateMaybeMessage<::storage_service::GetPageRequest_PageID>(Arena*);
template<> ::storage_service::GetPageResponse* Arena::CreateMaybeMessage<::storage_service::GetPageResponse>(Arena*);
template<> ::storage_service::LogWriteRequest* Arena::CreateMaybeMessage<::storage_service::LogWriteRequest>(Arena*);
template<> ::storage_service::LogWriteResponse* Arena::CreateMaybeMessage<::storage_service::LogWriteResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace storage_service {

// ===================================================================

class LogWriteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storage_service.LogWriteRequest) */ {
 public:
  inline LogWriteRequest() : LogWriteRequest(nullptr) {}
  ~LogWriteRequest() override;
  explicit PROTOBUF_CONSTEXPR LogWriteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogWriteRequest(const LogWriteRequest& from);
  LogWriteRequest(LogWriteRequest&& from) noexcept
    : LogWriteRequest() {
    *this = ::std::move(from);
  }

  inline LogWriteRequest& operator=(const LogWriteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogWriteRequest& operator=(LogWriteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogWriteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogWriteRequest* internal_default_instance() {
    return reinterpret_cast<const LogWriteRequest*>(
               &_LogWriteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogWriteRequest& a, LogWriteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LogWriteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogWriteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogWriteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogWriteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogWriteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LogWriteRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogWriteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storage_service.LogWriteRequest";
  }
  protected:
  explicit LogWriteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogFieldNumber = 1,
  };
  // string log = 1;
  void clear_log();
  const std::string& log() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_log(ArgT0&& arg0, ArgT... args);
  std::string* mutable_log();
  PROTOBUF_NODISCARD std::string* release_log();
  void set_allocated_log(std::string* log);
  private:
  const std::string& _internal_log() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log(const std::string& value);
  std::string* _internal_mutable_log();
  public:

  // @@protoc_insertion_point(class_scope:storage_service.LogWriteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr log_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_storage_5fservice_2eproto;
};
// -------------------------------------------------------------------

class LogWriteResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:storage_service.LogWriteResponse) */ {
 public:
  inline LogWriteResponse() : LogWriteResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR LogWriteResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogWriteResponse(const LogWriteResponse& from);
  LogWriteResponse(LogWriteResponse&& from) noexcept
    : LogWriteResponse() {
    *this = ::std::move(from);
  }

  inline LogWriteResponse& operator=(const LogWriteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogWriteResponse& operator=(LogWriteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogWriteResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogWriteResponse* internal_default_instance() {
    return reinterpret_cast<const LogWriteResponse*>(
               &_LogWriteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LogWriteResponse& a, LogWriteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LogWriteResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogWriteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogWriteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogWriteResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const LogWriteResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const LogWriteResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storage_service.LogWriteResponse";
  }
  protected:
  explicit LogWriteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:storage_service.LogWriteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  friend struct ::TableStruct_storage_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetPageRequest_PageID final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storage_service.GetPageRequest.PageID) */ {
 public:
  inline GetPageRequest_PageID() : GetPageRequest_PageID(nullptr) {}
  ~GetPageRequest_PageID() override;
  explicit PROTOBUF_CONSTEXPR GetPageRequest_PageID(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetPageRequest_PageID(const GetPageRequest_PageID& from);
  GetPageRequest_PageID(GetPageRequest_PageID&& from) noexcept
    : GetPageRequest_PageID() {
    *this = ::std::move(from);
  }

  inline GetPageRequest_PageID& operator=(const GetPageRequest_PageID& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPageRequest_PageID& operator=(GetPageRequest_PageID&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPageRequest_PageID& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPageRequest_PageID* internal_default_instance() {
    return reinterpret_cast<const GetPageRequest_PageID*>(
               &_GetPageRequest_PageID_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetPageRequest_PageID& a, GetPageRequest_PageID& b) {
    a.Swap(&b);
  }
  inline void Swap(GetPageRequest_PageID* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPageRequest_PageID* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPageRequest_PageID* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetPageRequest_PageID>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetPageRequest_PageID& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetPageRequest_PageID& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPageRequest_PageID* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storage_service.GetPageRequest.PageID";
  }
  protected:
  explicit GetPageRequest_PageID(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFdFieldNumber = 1,
    kPageNoFieldNumber = 2,
  };
  // sint32 fd = 1;
  void clear_fd();
  int32_t fd() const;
  void set_fd(int32_t value);
  private:
  int32_t _internal_fd() const;
  void _internal_set_fd(int32_t value);
  public:

  // sint32 page_no = 2;
  void clear_page_no();
  int32_t page_no() const;
  void set_page_no(int32_t value);
  private:
  int32_t _internal_page_no() const;
  void _internal_set_page_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:storage_service.GetPageRequest.PageID)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t fd_;
  int32_t page_no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_storage_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetPageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storage_service.GetPageRequest) */ {
 public:
  inline GetPageRequest() : GetPageRequest(nullptr) {}
  ~GetPageRequest() override;
  explicit PROTOBUF_CONSTEXPR GetPageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetPageRequest(const GetPageRequest& from);
  GetPageRequest(GetPageRequest&& from) noexcept
    : GetPageRequest() {
    *this = ::std::move(from);
  }

  inline GetPageRequest& operator=(const GetPageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPageRequest& operator=(GetPageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPageRequest* internal_default_instance() {
    return reinterpret_cast<const GetPageRequest*>(
               &_GetPageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetPageRequest& a, GetPageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetPageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetPageRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetPageRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetPageRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storage_service.GetPageRequest";
  }
  protected:
  explicit GetPageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GetPageRequest_PageID PageID;

  // accessors -------------------------------------------------------

  enum : int {
    kPageIdFieldNumber = 1,
  };
  // .storage_service.GetPageRequest.PageID page_id = 1;
  bool has_page_id() const;
  private:
  bool _internal_has_page_id() const;
  public:
  void clear_page_id();
  const ::storage_service::GetPageRequest_PageID& page_id() const;
  PROTOBUF_NODISCARD ::storage_service::GetPageRequest_PageID* release_page_id();
  ::storage_service::GetPageRequest_PageID* mutable_page_id();
  void set_allocated_page_id(::storage_service::GetPageRequest_PageID* page_id);
  private:
  const ::storage_service::GetPageRequest_PageID& _internal_page_id() const;
  ::storage_service::GetPageRequest_PageID* _internal_mutable_page_id();
  public:
  void unsafe_arena_set_allocated_page_id(
      ::storage_service::GetPageRequest_PageID* page_id);
  ::storage_service::GetPageRequest_PageID* unsafe_arena_release_page_id();

  // @@protoc_insertion_point(class_scope:storage_service.GetPageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::storage_service::GetPageRequest_PageID* page_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_storage_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetPageResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storage_service.GetPageResponse) */ {
 public:
  inline GetPageResponse() : GetPageResponse(nullptr) {}
  ~GetPageResponse() override;
  explicit PROTOBUF_CONSTEXPR GetPageResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetPageResponse(const GetPageResponse& from);
  GetPageResponse(GetPageResponse&& from) noexcept
    : GetPageResponse() {
    *this = ::std::move(from);
  }

  inline GetPageResponse& operator=(const GetPageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPageResponse& operator=(GetPageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPageResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPageResponse* internal_default_instance() {
    return reinterpret_cast<const GetPageResponse*>(
               &_GetPageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GetPageResponse& a, GetPageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetPageResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPageResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetPageResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetPageResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetPageResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPageResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storage_service.GetPageResponse";
  }
  protected:
  explicit GetPageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // string data = 1;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:storage_service.GetPageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_storage_5fservice_2eproto;
};
// ===================================================================

class StorageService_Stub;

class StorageService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline StorageService() {};
 public:
  virtual ~StorageService();

  typedef StorageService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void LogWrite(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::storage_service::LogWriteRequest* request,
                       ::storage_service::LogWriteResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void GetPage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::storage_service::GetPageRequest* request,
                       ::storage_service::GetPageResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(StorageService);
};

class StorageService_Stub : public StorageService {
 public:
  StorageService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  StorageService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~StorageService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements StorageService ------------------------------------------

  void LogWrite(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::storage_service::LogWriteRequest* request,
                       ::storage_service::LogWriteResponse* response,
                       ::google::protobuf::Closure* done);
  void GetPage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::storage_service::GetPageRequest* request,
                       ::storage_service::GetPageResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(StorageService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogWriteRequest

// string log = 1;
inline void LogWriteRequest::clear_log() {
  log_.ClearToEmpty();
}
inline const std::string& LogWriteRequest::log() const {
  // @@protoc_insertion_point(field_get:storage_service.LogWriteRequest.log)
  return _internal_log();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogWriteRequest::set_log(ArgT0&& arg0, ArgT... args) {
 
 log_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storage_service.LogWriteRequest.log)
}
inline std::string* LogWriteRequest::mutable_log() {
  std::string* _s = _internal_mutable_log();
  // @@protoc_insertion_point(field_mutable:storage_service.LogWriteRequest.log)
  return _s;
}
inline const std::string& LogWriteRequest::_internal_log() const {
  return log_.Get();
}
inline void LogWriteRequest::_internal_set_log(const std::string& value) {
  
  log_.Set(value, GetArenaForAllocation());
}
inline std::string* LogWriteRequest::_internal_mutable_log() {
  
  return log_.Mutable(GetArenaForAllocation());
}
inline std::string* LogWriteRequest::release_log() {
  // @@protoc_insertion_point(field_release:storage_service.LogWriteRequest.log)
  return log_.Release();
}
inline void LogWriteRequest::set_allocated_log(std::string* log) {
  if (log != nullptr) {
    
  } else {
    
  }
  log_.SetAllocated(log, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (log_.IsDefault()) {
    log_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storage_service.LogWriteRequest.log)
}

// -------------------------------------------------------------------

// LogWriteResponse

// -------------------------------------------------------------------

// GetPageRequest_PageID

// sint32 fd = 1;
inline void GetPageRequest_PageID::clear_fd() {
  fd_ = 0;
}
inline int32_t GetPageRequest_PageID::_internal_fd() const {
  return fd_;
}
inline int32_t GetPageRequest_PageID::fd() const {
  // @@protoc_insertion_point(field_get:storage_service.GetPageRequest.PageID.fd)
  return _internal_fd();
}
inline void GetPageRequest_PageID::_internal_set_fd(int32_t value) {
  
  fd_ = value;
}
inline void GetPageRequest_PageID::set_fd(int32_t value) {
  _internal_set_fd(value);
  // @@protoc_insertion_point(field_set:storage_service.GetPageRequest.PageID.fd)
}

// sint32 page_no = 2;
inline void GetPageRequest_PageID::clear_page_no() {
  page_no_ = 0;
}
inline int32_t GetPageRequest_PageID::_internal_page_no() const {
  return page_no_;
}
inline int32_t GetPageRequest_PageID::page_no() const {
  // @@protoc_insertion_point(field_get:storage_service.GetPageRequest.PageID.page_no)
  return _internal_page_no();
}
inline void GetPageRequest_PageID::_internal_set_page_no(int32_t value) {
  
  page_no_ = value;
}
inline void GetPageRequest_PageID::set_page_no(int32_t value) {
  _internal_set_page_no(value);
  // @@protoc_insertion_point(field_set:storage_service.GetPageRequest.PageID.page_no)
}

// -------------------------------------------------------------------

// GetPageRequest

// .storage_service.GetPageRequest.PageID page_id = 1;
inline bool GetPageRequest::_internal_has_page_id() const {
  return this != internal_default_instance() && page_id_ != nullptr;
}
inline bool GetPageRequest::has_page_id() const {
  return _internal_has_page_id();
}
inline void GetPageRequest::clear_page_id() {
  if (GetArenaForAllocation() == nullptr && page_id_ != nullptr) {
    delete page_id_;
  }
  page_id_ = nullptr;
}
inline const ::storage_service::GetPageRequest_PageID& GetPageRequest::_internal_page_id() const {
  const ::storage_service::GetPageRequest_PageID* p = page_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::storage_service::GetPageRequest_PageID&>(
      ::storage_service::_GetPageRequest_PageID_default_instance_);
}
inline const ::storage_service::GetPageRequest_PageID& GetPageRequest::page_id() const {
  // @@protoc_insertion_point(field_get:storage_service.GetPageRequest.page_id)
  return _internal_page_id();
}
inline void GetPageRequest::unsafe_arena_set_allocated_page_id(
    ::storage_service::GetPageRequest_PageID* page_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(page_id_);
  }
  page_id_ = page_id;
  if (page_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:storage_service.GetPageRequest.page_id)
}
inline ::storage_service::GetPageRequest_PageID* GetPageRequest::release_page_id() {
  
  ::storage_service::GetPageRequest_PageID* temp = page_id_;
  page_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::storage_service::GetPageRequest_PageID* GetPageRequest::unsafe_arena_release_page_id() {
  // @@protoc_insertion_point(field_release:storage_service.GetPageRequest.page_id)
  
  ::storage_service::GetPageRequest_PageID* temp = page_id_;
  page_id_ = nullptr;
  return temp;
}
inline ::storage_service::GetPageRequest_PageID* GetPageRequest::_internal_mutable_page_id() {
  
  if (page_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::storage_service::GetPageRequest_PageID>(GetArenaForAllocation());
    page_id_ = p;
  }
  return page_id_;
}
inline ::storage_service::GetPageRequest_PageID* GetPageRequest::mutable_page_id() {
  ::storage_service::GetPageRequest_PageID* _msg = _internal_mutable_page_id();
  // @@protoc_insertion_point(field_mutable:storage_service.GetPageRequest.page_id)
  return _msg;
}
inline void GetPageRequest::set_allocated_page_id(::storage_service::GetPageRequest_PageID* page_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete page_id_;
  }
  if (page_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(page_id);
    if (message_arena != submessage_arena) {
      page_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, page_id, submessage_arena);
    }
    
  } else {
    
  }
  page_id_ = page_id;
  // @@protoc_insertion_point(field_set_allocated:storage_service.GetPageRequest.page_id)
}

// -------------------------------------------------------------------

// GetPageResponse

// string data = 1;
inline void GetPageResponse::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& GetPageResponse::data() const {
  // @@protoc_insertion_point(field_get:storage_service.GetPageResponse.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetPageResponse::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storage_service.GetPageResponse.data)
}
inline std::string* GetPageResponse::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:storage_service.GetPageResponse.data)
  return _s;
}
inline const std::string& GetPageResponse::_internal_data() const {
  return data_.Get();
}
inline void GetPageResponse::_internal_set_data(const std::string& value) {
  
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* GetPageResponse::_internal_mutable_data() {
  
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* GetPageResponse::release_data() {
  // @@protoc_insertion_point(field_release:storage_service.GetPageResponse.data)
  return data_.Release();
}
inline void GetPageResponse::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storage_service.GetPageResponse.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace storage_service

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_storage_5fservice_2eproto
